package com.bangmaple.bangmaplenhentaihelper;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;
import mdlaf.MaterialLookAndFeel;

/**
 *
 * @author bangmaple
 */
public class ThumbnailForm extends javax.swing.JFrame {

    private NhentaiDTO dto;

    /**
     * Creates new form ThumbnailForm
     */
    public ThumbnailForm() {
        this.setLocationRelativeTo(null);
        initComponents();
        btnArtist.setHorizontalTextPosition(SwingConstants.LEFT);
        btnCategories.setHorizontalTextPosition(SwingConstants.LEFT);
        btnLanguage.setHorizontalTextPosition(SwingConstants.LEFT);
        load();
    }

    public ThumbnailForm(NhentaiDTO dto) {
        this.dto = dto;
        initComponents();

        load();

    }

    private void load() {
        try {
            URL url = new URL("https://t.nhentai.net/galleries/" + dto.getMedia_id() + "/cover.jpg");
            URLConnection connection = url.openConnection();
            connection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 5.1; rv:19.0) Gecko/20100101 Firefox/19.0");
            connection.connect();
            System.out.println(saveImage(dto.getMedia_id(), connection.getInputStream()));
            txtThumbnail.setText("");
            Icon icon = new ImageIcon(new ImageIcon(dto.getMedia_id() + "/cover.jpg").getImage().getScaledInstance(350, 479, java.awt.Image.SCALE_SMOOTH));
            txtThumbnail.setIcon(icon);
            System.out.println(dto.getTitle());
            txtEng.setText(dto.getTitle().getEnglish());
            txtJap.setText(dto.getTitle().getJapanese());
            // btnArtist.setText(dto.getTags()[0].getName());
            IconFontSwing.register(FontAwesome.getIconFont());
            Icon iconFav = IconFontSwing.buildIcon(FontAwesome.HEART, 15);
            Icon iconDownload = IconFontSwing.buildIcon(FontAwesome.DOWNLOAD, 15);
            Icon iconRead = IconFontSwing.buildIcon(FontAwesome.EYE, 15);
            btnRead.setIcon(iconRead);
            btnRead.setText("Continue Reading");
            btnDownload.setIcon(iconDownload);
            btnFav.setIcon(iconFav);
            txtPage.setText("Total " + dto.getNum_pages().toString() + " pages");
            txtTimeAgo.setText("Updated at " + new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date(Long.parseLong(dto.getUpload_date() + "000"))));
            btnFav.setText("Favorites (" + String.valueOf(dto.getNum_favories()) + ")");
            for (InnerTag tag : dto.getTags()) {
                if (tag.getType().equals("artist")) {
                    btnArtist.setText(tag.getName() + " (" + tag.getCount() + " )");
                }
                if (tag.getType().equals("language")) {
                    btnLanguage.setText(tag.getName() + " (" + tag.getCount() + " )");
                }
                if (tag.getType().equals("category")) {
                    btnCategories.setText(tag.getName() + " (" + tag.getCount() + " )");
                }
            }
        } catch (Exception e) {

        }
    }

    private String saveImage(final String mediaID, InputStream stream) {
        try {
            if (!new File(mediaID).isDirectory()) {
                BufferedImage image = ImageIO.read(stream);
                System.out.println(new File("logo.png").getAbsolutePath());
                File imageDir = new File(mediaID + "/" + "cover" + "." + "jpg");
                imageDir.getParentFile().mkdirs();
                ImageIO.write(image, "jpg", imageDir);
            }
        } catch (IOException e) {

        }
        return "cover" + "." + "jpg";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtThumbnail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnArtist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLanguage = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCategories = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEng = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJap = new javax.swing.JTextArea();
        btnFav = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        txtPage = new javax.swing.JLabel();
        txtTimeAgo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRead = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtThumbnail.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Artist:");

        btnArtist.setText("jButton1");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Language:");

        btnLanguage.setText("jButton1");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Categories:");

        btnCategories.setText("jButton2");

        txtEng.setColumns(20);
        txtEng.setRows(5);
        jScrollPane1.setViewportView(txtEng);

        txtJap.setColumns(20);
        txtJap.setRows(5);
        jScrollPane2.setViewportView(txtJap);

        btnFav.setBackground(new java.awt.Color(255, 204, 204));
        btnFav.setForeground(new java.awt.Color(255, 0, 0));
        btnFav.setText("jButton1");

        btnDownload.setText("Download");

        txtPage.setText("jLabel4");

        txtTimeAgo.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Tags:");

        btnRead.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtThumbnail, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPage)
                            .addComponent(txtTimeAgo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(22, 22, 22)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRead, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFav, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtThumbnail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(114, 114, 114))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArtist)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLanguage)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnCategories))
                        .addGap(18, 18, 18)
                        .addComponent(txtPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimeAgo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnFav, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialLookAndFeelKanjiHelper()));
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ThumbnailForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThumbnailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtist;
    private javax.swing.JButton btnCategories;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnFav;
    private javax.swing.JButton btnLanguage;
    private javax.swing.JButton btnRead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEng;
    private javax.swing.JTextArea txtJap;
    private javax.swing.JLabel txtPage;
    private javax.swing.JLabel txtThumbnail;
    private javax.swing.JLabel txtTimeAgo;
    // End of variables declaration//GEN-END:variables
}
